version: 0.2
phases:
  install:
    commands:
      - echo installing serverless
      - npm install -g serverless

  pre_build:
    commands:
      - echo install dependencies

  build:
    commands:
      - echo deployment started on `date`
      - echo deploying with serverless frameworkVersion
      - sls deploy -s $ENV_NAME
  post_build:
    commands:
      - echo deployment completed on `date`
