org: samba73
console: true
service: hello-serverless

frameworkVersion: '3'


provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1
  stage: dev 
  memorySize: 256
  timeout: 5


functions:
  hello:
    handler: handler.hello
  add:
    handler: handler.add
    timeout: 10
    events:
      - http:
          path: /math/add
          method: POST
          cors: true